export function readme(projectName: string) {
  return `# ${projectName}

Generated by \`runner-dev new\` for Runner 6.2.

## Quick start

1. Install dependencies:
   - npm install
2. Start the dev server:
   - npm run dev

The server starts on http://localhost:1337

- GraphQL endpoint: http://localhost:1337/graphql (how to query your guts and live telemetry)
- Voyager UI: http://localhost:1337/voyager (how the guts of your app look like)
- Project docs: http://localhost:1337/docs (beautiful docs with live telemetry and easy task and event dispatching)

## Runner 6.2 notes

- Runtime task and resource ids are structural, so user resource segments stay in canonical ids.
- \`resource.subtree(...)\` can compose multiple policies with an array.
- Built-in async context accessors support safe probes via \`tryUse()\` and \`has()\`.
- Built-in task middleware such as \`cache\`, \`concurrency\`, and \`rateLimit\` can partition state per tenant via \`tenantScope\`.
- Subtree middleware conflicts now fail fast instead of silently deferring to local middleware.

## Scripts

- dev: Run with tsx watch (TypeScript ESM)
- build: Type-check and emit to dist
- start: Run built app
- test: Run Vitest once
- test:watch: Run Vitest in watch mode

## Useful CLI commands

These commands are available from \`@bluelibs/runner-dev\`:

- Query your API:
  - ENDPOINT=http://localhost:1337/graphql npx runner-dev query 'query { tasks { id } }' --format pretty
- Print the GraphQL schema SDL:
  - npx runner-dev schema sdl --endpoint http://localhost:1337/graphql

`;
}
