import fs from "node:fs/promises";
import path from "node:path";

const repoRoot = path.resolve(__dirname, "..");
const skillRoot = path.join(repoRoot, "skills", "runner-dev");
const referencesDir = path.join(skillRoot, "references");
const generatedNotice =
  "<!-- Generated by scripts/prepare-skills.ts. Do not edit directly. -->";

async function ensureDir(dirPath: string) {
  await fs.mkdir(dirPath, { recursive: true });
}

async function writeFile(targetPath: string, contents: string) {
  await fs.writeFile(targetPath, contents, "utf8");
}

async function copyReferenceFile(
  sourceFileName: string,
  targetFileName?: string
) {
  const sourcePath = path.join(repoRoot, sourceFileName);
  const targetPath = path.join(
    referencesDir,
    targetFileName ?? sourceFileName
  );

  const contents = await fs.readFile(sourcePath, "utf8");
  await writeFile(targetPath, `${generatedNotice}\n\n${contents}`);
}

async function writeSkillFile() {
  const skillContents = [
    "---",
    "name: runner-dev",
    "description: Use when working on @bluelibs/runner-dev itself, especially for docs UI behavior, introspection resources, GraphQL tooling, MCP helpers, telemetry surfaces, and agent-facing documentation. Start here when the task needs runner-dev-specific context instead of the general Runner framework skill.",
    "---",
    "",
    generatedNotice,
    "",
    "# Runner Dev",
    "",
    "Start with `./references/COMPACT_GUIDE.md`.",
    "It is the compact runner-dev guide generated from the repo's `AI.md` and should stay aligned with the current toolkit behavior.",
    "",
    "Use `./references/README.md` when the task needs installation, CLI, or user-facing usage details.",
    "",
    "Use this skill when the task involves:",
    "",
    "- docs UI behavior, `/docs/data`, or in-app documentation delivery",
    "- MCP helpers, GraphQL tooling, introspection resources, or chat context wiring",
    "- live telemetry, hot-swapping, CLI surfaces, or other runner-dev tooling",
    "- agent-facing documentation that must stay aligned with `COMPACT_GUIDE.md` and `README.md`",
    "",
    "Reach for the general Runner skill when the problem is about framework design rather than runner-dev's tooling surface.",
  ].join("\n");

  await writeFile(path.join(skillRoot, "SKILL.md"), `${skillContents}\n`);
}

async function prepareSkills() {
  await ensureDir(referencesDir);
  await fs.rm(path.join(referencesDir, "AI.md"), { force: true });
  await writeSkillFile();
  await copyReferenceFile("AI.md", "COMPACT_GUIDE.md");
  await copyReferenceFile("README.md");
}

prepareSkills().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`Failed to prepare skills: ${message}`);
  process.exitCode = 1;
});
