/*
  Sync src/version.ts with package.json version.
*/
import fs from 'fs';
import path from 'path';

const root = process.cwd();
const pkgPath = path.join(root, 'package.json');
const outPath = path.join(root, 'src', 'version.ts');

const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8')) as { version?: string };
const version = pkg.version || 'unknown';

const banner = `// Auto-generated by scripts/sync-version.ts. Do not edit manually.\n`;
const content = `${banner}const v = '${version}';\nexport default v;\n`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content);

// eslint-disable-next-line no-console
console.log(`[sync-version] Wrote ${outPath} with version ${version}`);
